{ fetchNuGet }: [
  (fetchNuGet { pname = "dnlib"; version = "3.3.2"; hash = "sha256-qqFl/AJXhLR8Z/UZUpCZ19JVAtdn9fC4JutHGvM5LfE="; })
  (fetchNuGet { pname = "Microsoft.AspNetCore.App.Ref"; version = "3.1.10"; hash = "sha256-51D1XkqFMPHJzOmt1HQ0Bf1n9K0auwEyxTJuqA/8xHY="; })
  (fetchNuGet { pname = "Microsoft.AspNetCore.App.Runtime.linux-x64"; version = "3.1.32"; hash = "sha256-OV3Ie8JGTEwNI4Y6DJFh+ZUrBTwrSdFjEbfljfAwn3s="; })
  (fetchNuGet { pname = "Microsoft.NETCore.App"; version = "2.1.0"; hash = "sha256-RJksv5W7LhWJYGmkwYHfiU0s9XLCvT05KxSMz6U1/OE="; })
  (fetchNuGet { pname = "Microsoft.NETCore.App.Host.linux-x64"; version = "3.1.32"; hash = "sha256-ajR6pZv0zuzWDyxEnWtAuhasV5biV5lvweEbefTISiM="; })
  (fetchNuGet { pname = "Microsoft.NETCore.App.Ref"; version = "3.1.0"; hash = "sha256-nuAvHwmJ2s3Ob1qNDH1+uV3awOZaWlaV3FenTmPUWyM="; })
  (fetchNuGet { pname = "Microsoft.NETCore.App.Runtime.linux-x64"; version = "3.1.32"; hash = "sha256-h4HjfRnvH81dW84S3TCPcCfxeQLiLN7b1ZleRNsprFY="; })
  (fetchNuGet { pname = "Microsoft.NETCore.DotNetAppHost"; version = "2.1.0"; hash = "sha256-LV8pnNFsKGFONyCTGsd8qB5A+EUIiyvbYWAr0eOEFoI="; })
  (fetchNuGet { pname = "Microsoft.NETCore.DotNetHostPolicy"; version = "2.1.0"; hash = "sha256-FqQm4BLznzRmF1nhk3nEwrdeAdCY35eBmHk6/4+MCPY="; })
  (fetchNuGet { pname = "Microsoft.NETCore.DotNetHostResolver"; version = "2.1.0"; hash = "sha256-5nQTmMhaEvbuT+1f7u0t0tEK3SCVUeXhsExq8tiYBI0="; })
  (fetchNuGet { pname = "Microsoft.NETCore.Platforms"; version = "2.1.0"; hash = "sha256-v09ltBAKTX8iAKuU2nCl+Op/ilVJQ0POZUh2z+u0rVo="; })
  (fetchNuGet { pname = "Microsoft.NETCore.Platforms"; version = "3.1.0"; hash = "sha256-cnygditsEaU86bnYtIthNMymAHqaT/sf9Gjykhzqgb0="; })
  (fetchNuGet { pname = "Microsoft.NETCore.Targets"; version = "2.1.0"; hash = "sha256-+KdWdA9I392SRqMb9KaiiRZatfvJ9RcdbtyGUkpHW7U="; })
  (fetchNuGet { pname = "Microsoft.Win32.SystemEvents"; version = "4.7.0"; hash = "sha256-GHxnD1Plb32GJWVWSv0Y51Kgtlb+cdKgOYVBYZSgVF4="; })
  (fetchNuGet { pname = "NETStandard.Library"; version = "2.0.3"; hash = "sha256-Prh2RPebz/s8AzHb2sPHg3Jl8s31inv9k+Qxd293ybo="; })
  (fetchNuGet { pname = "runtime.linux-x64.Microsoft.NETCore.App"; version = "2.1.0"; hash = "sha256-qFtPLe3t/V9DZTaYhAO6MbVsyzH4hcQQUvyIJ6ywbEw="; })
  (fetchNuGet { pname = "runtime.linux-x64.Microsoft.NETCore.DotNetAppHost"; version = "2.1.0"; hash = "sha256-NMuEFKc68Vn4bVoX6kdGSQeyDpktUYliUg6Lbj4E8FU="; })
  (fetchNuGet { pname = "runtime.linux-x64.Microsoft.NETCore.DotNetHostPolicy"; version = "2.1.0"; hash = "sha256-U/WlbUpImqPjZf075WgBOb1o1i1H3VOL4QbzHfQ9Itk="; })
  (fetchNuGet { pname = "runtime.linux-x64.Microsoft.NETCore.DotNetHostResolver"; version = "2.1.0"; hash = "sha256-vcB6FY1GDP+kTsmp9OXpPg50sXKqOSJzWUSuNlN1+rs="; })
  (fetchNuGet { pname = "System.Drawing.Common"; version = "4.7.0"; hash = "sha256-D3qG+xAe78lZHvlco9gHK2TEAM370k09c6+SQi873Hk="; })
  (fetchNuGet { pname = "System.Reflection.Emit"; version = "4.7.0"; hash = "sha256-Fw/CSRD+wajH1MqfKS3Q/sIrUH7GN4K+F+Dx68UPNIg="; })
  (fetchNuGet { pname = "System.Reflection.Emit.Lightweight"; version = "4.7.0"; hash = "sha256-V0Wz/UUoNIHdTGS9e1TR89u58zJjo/wPUWw6VaVyclU="; })
]
